plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  MinDigits: 4
  Strict: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]

Style/Documentation:
  Enabled: false
